name: beta_project
description: Home management system using IoT

documentation: https://github.com/Mawueugiio/homesys/blob/dev/README.md

repository: https://github.com/Mawueugiio/homesys/tree/dev

authors:
  - Eugenia

publish_to: "github.com"

version: 0.0.1+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  google_fonts: ^1.1.0
  undraw: ^1.0.2
  get_it: ^4.0.2
  shared_preferences: ^0.5.7+2
  flutter_local_notifications: ^1.4.3
  auto_route: ^0.5.0
  eva_icons_flutter: ^2.0.0
  flutter_staggered_animations: ^0.1.2
  flutter_staggered_grid_view: ^0.3.0
  timeago: ^2.0.26
  bloc: ^4.0.0
  flutter_bloc: ^4.0.0
  json_annotation: ^3.0.1
  cached_network_image: ^2.2.0+1
  image_picker: ^0.6.6+1
  equatable: ^1.1.1
  sliding_sheet: ^0.3.5
  path_provider: ^1.6.8
  path: ^1.7.0
  permission_handler: ^5.0.0+hotfix.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Route generator
  auto_route_generator: ^0.5.0

  # Build scripts
  build_runner: ^1.10.0

  # Launcher Icons generator for flutter
  flutter_launcher_icons: ^0.7.5

  # Mockito (for testing)
  mockito: ^4.1.1

  # Serialise Json
  json_serializable: ^3.2.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.webp"

flutter:
  uses-material-design: true
  assets:
    - assets/logo/logo.webp
    - assets/logo/2x/logo.webp
    - assets/logo/3x/logo.webp
    - assets/logo/4x/logo.webp